{"name": "CVE-2015-2316", "public_date": "2015-03-18T00:00:00", "package_state": [{"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 4.0", "package_name": "Django14", "cpe": "cpe:/a:redhat:openstack:4"}, {"fix_state": "Fix deferred", "product_name": "Red Hat Enterprise Linux OpenStack Platform 5.0 (Icehouse) for RHEL 6", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:5"}, {"fix_state": "Fix deferred", "product_name": "Red Hat Enterprise Linux OpenStack Platform 6.0 (Juno) for RHEL 7", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:6"}, {"fix_state": "Not affected", "product_name": "Red Hat Subscription Asset Manager 1", "package_name": "Django", "cpe": "cpe:/a:redhat:rhel_sam:1"}], "acknowledgement": "\nRed Hat would like to thank the upstream Django project for reporting this issue.\n    ", "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "upstream_fix": "Django 1.8rc1, Django 1.7.7, Django 1.6.11", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1202809", "description": "\nCVE-2015-2316 Django: possible denial of service in strip_tags()\n    ", "id": "1202809"}, "references": ["\nhttps://www.djangoproject.com/weblog/2015/mar/18/security-releases/\n    "], "details": ["\nThe utils.html.strip_tags function in Django 1.6.x before 1.6.11, 1.7.x before 1.7.7, and 1.8.x before 1.8c1, when using certain versions of Python, allows remote attackers to cause a denial of service (infinite loop) by increasing the length of the input string.\n    "], "cwe": "CWE-835", "cvss": {"cvss_scoring_vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P", "status": "draft", "cvss_base_score": "4.3"}}