{"name": "CVE-2014-2573", "public_date": "2014-01-20T00:00:00", "package_state": [{"fix_state": "Will not fix", "product_name": "Red Hat Enterprise Linux OpenStack Platform 3.0", "package_name": "openstack-nova", "cpe": "cpe:/a:redhat:openstack:3"}, {"fix_state": "Will not fix", "product_name": "Red Hat Enterprise Linux OpenStack Platform 4.0", "package_name": "openstack-nova", "cpe": "cpe:/a:redhat:openstack:4"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 5.0 (Icehouse) for RHEL 6", "package_name": "openstack-nova", "cpe": "cpe:/a:redhat:openstack:5"}], "acknowledgement": "\nThis issue was discovered by Jaroslav Henner of Red Hat.\n    ", "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1080289", "description": "\nCVE-2014-2573 openstack-nova: Nova VMware driver leaks rescued images\n    ", "id": "1080289"}, "details": ["\nThe VMWare driver in OpenStack Compute (Nova) 2013.2 through 2013.2.2 does not properly put VMs into RESCUE status, which allows remote authenticated users to bypass the quota limit and cause a denial of service (resource consumption) by requesting the VM be put into rescue and then deleting the image.\n    ", "\nA denial of service flaw was found in the nova VMware driver. An authenticated user could exceed their quota by placing an image into rescue and then deleting it, causing the rescue image to be left behind. Note that only setups using the nova VMware driver were affected.\n    "], "cwe": "CWE-400", "cvss": {"cvss_scoring_vector": "AV:N/AC:L/Au:S/C:N/I:N/A:P", "status": "draft", "cvss_base_score": "4.0"}}