{"name": "CVE-2013-7393", "public_date": "2013-08-30T00:00:00", "package_state": [{"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 5", "package_name": "subversion", "cpe": "cpe:/o:redhat:enterprise_linux:5"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 6", "package_name": "subversion", "cpe": "cpe:/o:redhat:enterprise_linux:6"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 7", "package_name": "subversion", "cpe": "cpe:/o:redhat:enterprise_linux:7"}], "acknowledgement": "\nRed Hat would like to thank Ben Reser of the Apache Subversion project for reporting this issue. Upstream acknowledges Daniel Shahaf of Apache Infrastructure as the original issue reporter.\n    ", "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "upstream_fix": "subversion 1.8.3", "threat_severity": "Low", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1000194", "description": "\nCVE-2013-4262 CVE-2013-7393 subversion: svnwcsub.py and irkerbridge.py are vulnerable to symlink attack\n    ", "id": "1000194"}, "references": ["\nhttp://subversion.apache.org/security/CVE-2013-4262-advisory.txt\n    "], "details": ["\nThe daemonize.py module in Subversion 1.8.0 before 1.8.2 allows local users to gain privileges via a symlink attack on the pid file created for (1) svnwcsub.py or (2) irkerbridge.py when the --pidfile option is used.  NOTE: this issue was SPLIT from CVE-2013-4262 based on different affected versions (ADT3).\n    "], "statement": "\nNot vulnerable.  This issue did not affect the versions of subversion as shipped with Red Hat Enterprise Linux 5 or 6, as they did not ship the vulnerable versions of subversion.\n    ", "cvss": {"cvss_scoring_vector": "AV:L/AC:H/Au:N/C:N/I:P/A:P", "status": "draft", "cvss_base_score": "2.6"}}