{"name": "CVE-2015-8949", "public_date": "2015-11-14T00:00:00", "package_state": [{"fix_state": "Not affected", "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux", "package_name": "perl516-perl-DBD-MySQL", "cpe": "cpe:/a:redhat:rhel_software_collections:2"}, {"fix_state": "Will not fix", "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux", "package_name": "rh-perl520-perl-DBD-MySQL", "cpe": "cpe:/a:redhat:rhel_software_collections:2"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 5", "package_name": "perl-DBD-MySQL", "cpe": "cpe:/o:redhat:enterprise_linux:5"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 6", "package_name": "perl-DBD-MySQL", "cpe": "cpe:/o:redhat:enterprise_linux:6"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 7", "package_name": "perl-DBD-MySQL", "cpe": "cpe:/o:redhat:enterprise_linux:7"}], "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "cvss3": {"status": "draft", "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N", "cvss3_base_score": "3.7"}, "threat_severity": "Low", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1360279", "description": "\nCVE-2015-8949 perl-DBD-MySQL: Use after free when my_login fails\n    ", "id": "1360279"}, "details": ["\nUse-after-free vulnerability in the my_login function in DBD::mysql before 4.033_01 allows attackers to have unspecified impact by leveraging a call to mysql_errno after a failure of my_login.\n    "], "upstream_fix": "perl-DBD-MySQL 4.0.34", "cwe": "CWE-416", "cvss": {"cvss_scoring_vector": "AV:N/AC:H/Au:N/C:P/I:N/A:N", "status": "draft", "cvss_base_score": "2.6"}}