{"name": "CVE-2013-6484", "affected_release": [{"advisory": "RHSA-2014:0139", "release_date": "2014-02-05T00:00:00", "cpe": "cpe:/o:redhat:enterprise_linux:5", "product_name": "Red Hat Enterprise Linux 5", "package": "pidgin-2.6.6-32.el5"}, {"advisory": "RHSA-2014:0139", "release_date": "2014-02-05T00:00:00", "cpe": "cpe:/o:redhat:enterprise_linux:6", "product_name": "Red Hat Enterprise Linux 6", "package": "pidgin-2.7.9-27.el6"}], "public_date": "2014-01-28T00:00:00", "package_state": {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux 7", "package_name": "pidgin", "cpe": "cpe:/o:redhat:enterprise_linux:7"}, "acknowledgement": "\nRed Hat would like to thank the Pidgin project for reporting this issue.\n    ", "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "upstream_fix": "pidgin 2.10.8", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1057481", "description": "\nCVE-2013-6484 pidgin: DoS via specially-crafted stun messages\n    ", "id": "1057481"}, "references": ["\nhttp://pidgin.im/news/security/?id=79\n    "], "details": ["\nThe STUN protocol implementation in libpurple in Pidgin before 2.10.8 allows remote STUN servers to cause a denial of service (out-of-bounds write operation and application crash) by triggering a socket read error.\n    "], "cwe": "CWE-190", "cvss": {"cvss_scoring_vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P", "status": "verified", "cvss_base_score": "4.3"}}