{"public_date": "2016-02-01T00:00:00", "name": "CVE-2016-2048", "acknowledgement": "\nRed Hat would like to thank the upstream Django project for reporting this issue.\n    ", "package_state": [{"fix_state": "Not affected", "product_name": "Red Hat Ceph Storage 1.2", "package_name": "Django", "cpe": "cpe:/a:redhat:ceph_storage:1.2"}, {"fix_state": "Not affected", "product_name": "Red Hat Ceph Storage 1.3", "package_name": "Django", "cpe": "cpe:/a:redhat:ceph_storage:1.3"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 7.0 Operational Tools for RHEL 7", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack-optools:7"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 8.0 Operational Tools for RHEL 7", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack-optools:8"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 5.0 (Icehouse) for RHEL 6", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:5"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 6.0 (Juno) for RHEL 7", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:6"}, {"fix_state": "Not affected", "product_name": "Red Hat Enterprise Linux OpenStack Platform 7.0 (Kilo) for RHEL 7", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:7"}, {"fix_state": "Not affected", "product_name": "Red Hat OpenStack Platform 8.0 (Liberty)", "package_name": "python-django", "cpe": "cpe:/a:redhat:openstack:8"}, {"fix_state": "Not affected", "product_name": "Red Hat Subscription Asset Manager 1", "package_name": "Django", "cpe": "cpe:/a:redhat:rhel_sam:1"}], "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "upstream_fix": "Django 1.9.2", "threat_severity": "Low", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1302699", "description": "\nCVE-2016-2048 python-django: user with \"change\" but not \"add\" permission can create objects for ModelAdmin\n    ", "id": "1302699"}, "references": ["\nhttps://www.djangoproject.com/weblog/2016/feb/01/releases-192-and-189/\n    "], "details": ["\nDjango 1.9.x before 1.9.2, when ModelAdmin.save_as is set to True, allows remote authenticated users to bypass intended access restrictions and create ModelAdmin objects via the \"Save as New\" option when editing objects and leveraging the \"change\" permission.\n    "], "cvss": {"cvss_scoring_vector": "AV:N/AC:M/Au:S/C:N/I:P/A:N", "status": "draft", "cvss_base_score": "3.5"}}