{"name": "CVE-2013-0305", "affected_release": {"advisory": "RHSA-2013:0670", "release_date": "2013-03-21T00:00:00", "cpe": "cpe:/a:redhat:openstack:2::el6", "product_name": "OpenStack Folsom", "package": "Django14-1.4.4-1.el6ost"}, "public_date": "2013-02-19T00:00:00", "package_state": [{"fix_state": "Affected", "product_name": "RHOS Essex Release", "package_name": "Django", "cpe": "cpe:/a:redhat:openstack:1"}, {"fix_state": "Affected", "product_name": "Red Hat Subscription Asset Manager 1", "package_name": "Django", "cpe": "cpe:/a:redhat:rhel_sam:1"}], "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "threat_severity": "Moderate", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=913041", "description": "\nCVE-2013-0305 Django: Data leakage via admin history log\n    ", "id": "913041"}, "details": ["\nThe administrative interface for Django 1.3.x before 1.3.6, 1.4.x before 1.4.4, and 1.5 before release candidate 2 does not check permissions for the history view, which allows remote authenticated administrators to obtain sensitive object history information.\n    "], "cvss": {"cvss_scoring_vector": "AV:N/AC:L/Au:S/C:P/I:N/A:N", "status": "verified", "cvss_base_score": "4.0"}}