{"public_date": "2015-06-19T00:00:00", "name": "CVE-2015-6240", "package_state": [{"fix_state": "Not affected", "product_name": "Red Hat OpenShift Enterprise 3", "package_name": "ansible", "cpe": "cpe:/a:redhat:openshift:3"}, {"fix_state": "Not affected", "product_name": "OpenStack 10.0 Tools for RHEL 7", "package_name": "ansible", "cpe": "cpe:/a:redhat:openstack:10"}, {"fix_state": "Not affected", "product_name": "Red Hat Storage Console 2", "package_name": "ansible", "cpe": "cpe:/a:redhat:rhscon:2"}, {"fix_state": "Not affected", "product_name": "Red Hat Gluster Storage 3.0", "package_name": "ansible", "cpe": "cpe:/a:redhat:storage:3.0"}], "document_distribution": "Copyright \u00a9 2016 Red Hat, Inc. All rights reserved.", "upstream_fix": "Ansible 1.9.2", "threat_severity": "Important", "bugzilla": {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1243468", "description": "\nCVE-2015-6240 CVE-2015-3908 ansible: multiple issues fixed in 1.9.2\n    ", "id": "1243468"}, "references": ["\nhttp://www.ansible.com/security\n    "], "details": ["\nThe chroot, jail, and zone connection plugins in ansible before 1.9.2 allow local users to escape a restricted environment via a symlink attack.\n    "], "cvss": {"cvss_scoring_vector": "AV:N/AC:H/Au:N/C:C/I:C/A:C", "status": "draft", "cvss_base_score": "7.6"}}